### ISSUE TITLE
Login via proxy url does not take redirect_url param

### ISSUE THREAD

**Issue by ThePokeX** [felixrupp/user_cas#9]
- What led up to the situation?

      Clicking bookmark to favorites folder ( which created this: [owncloud's url]/index.php/login?redirect_url=%252Findex.php%252Fapps%252Ffiles%252F%253Fdir%253D%252F%2526view%253Dfavorites )

- What was the outcome of this action?

     After login with user_cas, ended up at home page.

- What outcome did you expect instead?

     Logging in and being directed to the favorites page.

By the way, thank you very much for keeping this app up to date. I appreciate the effort you have put into this!

**Comment by felixrupp** [comment]
Hi @ThePokeX,

it appears to me, that your OwnCloud session is terminated, so it redirects you to the OwnCloud login page with the `redirect_url` parameter attached, is that correct?

The current release version of user_cas should cover this `redirect_url` parameter, but i'll check that to be sure!

Thank you for the report!

**Comment by felixrupp** [comment]
I assume you used the current development branch on an Owncloud 10 installation? Then there really was a bug, missing out the correct url parameters. This is now fixed in the release/1.5.0 branch, see 1964d80b365a123384b4dca0fc617802ee5802f6

On Owncloud 9.1.6 the registration of the login button was implemented in the old style, so the bug only affected the development version for the future 1.5.0 version.

**Comment by ThePokeX** [comment]
I am still having the issue on an Owncloud 10 installation while on the release/1.5.0 branch.
I feel as though my configuration is incorrect, specifically Service URL. I currently have it as ```
https://[Host 
 url here]/owncloud/index.php/apps/user_cas/login
```
Is that correct?

**Comment by felixrupp** [comment]
Hi @ThePokeX 

Service URL should only be used, if you want to use your CAS client as a proxy client. If that’s not the case, please leave this blank! If you use it as a Proxy Server, please refer to the [phpcas documentation](https://wiki.jasig.org/display/CASC/phpCAS+examples#phpCASexamples-ACASproxy).

Regards

Felix

**Comment by ThePokeX** [comment]
Leaving the field blank causes the CAS server to redirect the browser to: `https://[Host url here]/index.php/apps/user_cas/login` which is not correct, the server is behind a reverse proxy.
Looks like that setting is correct after all, did some packet testing and it seems to be communicating correctly.
However, when the setting is disabled, the redirect parameter is being used successfully, but when I have a setting for Service URL, the redirect parameter is not used.

**Comment by felixrupp** [comment]
Hi @ThePokeX 

ok, now I understand your problem. At the moment, I’m not able to reproduce the bug, because there is no proxy server in my configuration. 

The internal phpCAS mechanism is working different, when using a service url for proxy setups, I will try to find a solution.

I will contact you, as soon as I have a solution, so you can test that in your config.


Thanks for you feedback and regards

Felix

**Comment by felixrupp** [comment]
Hi @ThePokeX ,

I investigated the problem. The redirect_url parameter can not be used with the service url, because the CAS server will then not validate your CAS ticket after authentication. I can’t find the according logic in the phpCAS library where this is implemented, so for now, it is not able to implement this.

Sorry!

**Comment by felixrupp** [comment]
Hi @ThePokeX 

i stumbled upon other errors and did a complete rewrite on the redirect_url engine. It’s now cookie based for better client-side differentiation between parallel users of the ownCloud instance.

The error you described above is fixed with that rewrite. Please test out the current [release-1.5.0 branch](/felixrupp/user_cas/tree/release/1.5.0).
